# Build stage
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /build
COPY . .
RUN mvn clean package -DskipTests

# Run stage
FROM alpine/java:17
WORKDIR /app
COPY --from=build /build/demo-client/target/demo-client-*.jar app.jar
COPY demo-client/src/main/resources/demo-root-ca.crt /app/demo-root-ca.crt
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]